### ISSUE TITLE
PAJ: Keybindings for junk/unjunk and lock/unlock

### ISSUE THREAD

**Issue by klingo** [klingo/ESO-PersonalAssistant#101]
>[14:39]
>Takit:
>	Or delete the item you mouse over (without the need to right click, destroy, confirm)
>	Or "lock" the item you mouse over
>	But I usually only use the "mark junk".
>	I feel it should be part of PA because it's about managing items. :)

**Comment by Eragos** [comment]
Hey! I also use delete keybinding from Dustman to move items to Junk - It's the last, only reason I use Dustman. Would be nice for me to see that in PAJ. So I can uninstall Dustman :)

**Comment by klingo** [comment]
Will come with the next update :)
