### ISSUE TITLE
PA: Add keybinding to summon assistants (banker/merchant)

### ISSUE THREAD

**Issue by klingo** [klingo/ESO-PersonalAssistant#142]

**Comment by Tjorkinthus** [comment]
I do it, if you want you can take the code https://www.esoui.com/downloads/info2481-OneKeyAssistant.html

**Comment by klingo** [comment]
I set this to low prio because the assistants can also be added to the quick actions bar and then call them with a single click. So I am not sure if this indeed still makes sense or can just be dropped.

**Comment by Tjorkinthus** [comment]
It make sense if you don't want to use a quickslot for each assistant and
put more different shortcut in bar.

**Comment by klingo** [comment]
Upon further consideration, I will not include this in Personal Assistant.
Reason: There is already a very lightweight addon that does that.
