### ISSUE TITLE
UI Error in Trade House

### ISSUE THREAD

**Issue by sivan-koren** [klingo/ESO-PersonalAssistant#145]
In controller mode UI.

When listing or searching items on guild stores.

user:/AddOns/PersonalAssistant/PersonalAssistantLoot/PALootItemIcons.lua:250: attempt to index a nil value

stack traceback: ' ' in function 'initHooksOnTradeHouse'

**Comment by klingo** [comment]
Hi 00sivan
Gamepad/Controller mode is not supported by this addon.
However, I will add a small change with the next version so that at least the error will no longer show up.

**Comment by sivan-koren** [comment]
That's perfect! It seems to work just fine otherwise. Great add-on. Very
cool!
