### ISSUE TITLE
Junkrules get ignored for unsellable junk

### ISSUE THREAD

**Issue by t2YU2m8l83** [klingo/ESO-PersonalAssistant#227]
I've set some things like "Mud Ball" or "Runebox: Juggler's Kinfe" as permanent junk but I still receive those items to my regular inventory and have to manually move them to the junk section.

**Comment by klingo** [comment]
How do you receive these items? By mail? There is an extra option that ignores marking items as junk that are received by mail.

**Comment by t2YU2m8l83** [comment]
In this case I received those items from the boxes I got after completing the winter event quests. But it shouldn't matter from where I receive those items, they should be destroyed up on sight. This Problem also applies to things like the daily login rewards.

**Comment by klingo** [comment]
I need to look into this more detailed, but might take a while because there is always only one attempt per day to check how daily login rewards are handled :)

**Comment by klingo** [comment]
More time needed for additional translations --> shifted to 2.4.19
