### ISSUE TITLE
Auto mark {Treasure} As Junk

### ISSUE THREAD

**Issue by TheHiveHelixLabs** [klingo/ESO-PersonalAssistant#229]
IT simply does not work....... my bag is full of Treasure items because it was not junking them like it was supposed to.....

**Comment by klingo** [comment]
Can you please be a bit more specific? Have you maybe the Quest Protection for Treasure Items enabled? This will prevent certain Treasure Items from being marked as junk.

**Comment by klingo** [comment]
Did not get any further feedback and cannot reproduce issue --> closed
