### ISSUE TITLE
Auto-Junk Rare Fish

### ISSUE THREAD

**Issue by t2YU2m8l83** [klingo/ESO-PersonalAssistant#231]
Rare fish is completely useless aside from the achievement therefore an option to auto-junk all rare fish should be implemented.

**Comment by klingo** [comment]
There already is an aoption to mark them as junk; unless you have enabled the exclusion for Rare Fish? Please check.

![image](https://user-images.githubusercontent.com/14639044/74980959-afee9280-5431-11ea-8cf0-ea66ea143b8f.png)

**Comment by t2YU2m8l83** [comment]
You should definitely rework the description or the functionality. I thought this only included the three fishes for the stattet event and not every rare fish...

**Comment by klingo** [comment]
If above toggle is turned on, then items with **SPECIALIZED_ITEMTYPE_COLLECTIBLE_RARE_FISH** are not marked as junk. 
Based on your feedback I understand that this also applies to other "regular" rare fishes, mhh..

Yes I will nee to rewrite the description then. Currently there is no way to distinguish rare fish needed for the event from other rare fish.
