### ISSUE TITLE
Deconstruction branch of PA

### ISSUE THREAD

**Issue by TagCdog** [klingo/ESO-PersonalAssistant#253]
Hi @klingo, I've tried to suggest this on [ESOUI ](https://www.esoui.com/forums/showthread.php?p=40846) but it seems like it is out-of-scope for other addons. I think PA is the perfect scope for this. There may be alternatives for doing this, but to my knowledge they aren't very end user friendly.

My request is to basically duplicate your junk feature except make it flag items as deconstructable with FCO ItemSaver. Even the user-friendly custom rules to mark an item as permanently deconstructable would be a godsend!

**Comment by klingo** [comment]
Hi, sorry but this extended logic is not planned for PersonalAssistant.
