### ISSUE TITLE
Request: Custom rules for junk/bank

### ISSUE THREAD

**Issue by thesimonho** [klingo/ESO-PersonalAssistant#254]
Possible to add custom rules for PA junk, in addition to simply marking as permanent junk?

For example, mark something as junk (or deposit in bank) if you have more than 100 in your bag? Or even better, an auto rule that will mark as junk/bank if you have more than 1 full stack of the item in your bag? This would be nice as a general option for things like soul gems, lock picks, repair kits etc.

**Comment by klingo** [comment]
Hi, sorry but this extended logic is not planned for PersonalAssistant.
