### ISSUE TITLE
PA Permanent Junk

### ISSUE THREAD

**Issue by freewheelr** [klingo/ESO-PersonalAssistant#314]
Hi,

First of all, thank you for the great work in creating a slick and clean addon for ESO. I use it a lot.

I have a suggestion/request for junk filters. Would it be possible to : 

- add a hotkey for permanent junk function so it is faster than going right click mark as permanent junk
- make them configurable (so that you can say select the traits and enchantment per item instead of having to do each trait and enchantment as a separate one)

R.

**Comment by freewheelr** [comment]
Two more while I'm at it:

- add option to add all items in a set to go to junk.... helps with moving bad sets to junk

**Comment by klingo** [comment]
Hi, thank you for your feedback.

> add a hotkey for permanent junk function so it is faster than going right click mark as permanent junk

good idea, I will consider it for a future version.

> make them configurable (so that you can say select the traits and enchantment per item instead of having to do each trait and enchantment as a separate one)

for now, that would exceed the desired complexity of PAJunk - it's difficult to balance the 'easy to use' aspect with a bigger level of customization.

> add option to add all items in a set to go to junk.... helps with moving bad sets to junk

this on the other hand should not be too difficult to add, will be considered as well :)

**Comment by freewheelr** [comment]
Cool, thanks for the feedback and consideraton. If you need a beta tester let me know

Kind Regards
________________________________

**Comment by freewheelr** [comment]
Just saw the permanent junk keybind in the changelog, ty. Testing is out later
