### ISSUE TITLE
Personal assistant is broken

### ISSUE THREAD

**Issue by hannibalem666** [klingo/ESO-PersonalAssistant#332]
i tried to bug report but thats broken also

i type /pa then try to reset to defult as the personal assistant is not depositing stuff in my bag, or sorting junk, it stopped working this morning, this is the error message i get. love the app btw its made things so much better for my life..

user:/AddOns/HarvestMap/Libs/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:326: function expected instead of nil
stack traceback:
user:/AddOns/HarvestMap/Libs/LibAddonMenu-2.0/LibAddonMenu-2.0.lua:326: in function 'm_callback'
EsoUI/Libraries/ZO_Dialog/ZO_Dialog.lua:77: in function 'HandleCallback'
EsoUI/Libraries/ZO_KeybindButton/ZO_KeybindButton.lua:194: in function 'ZO_KeybindButtonMixin:OnClicked'
EsoUI/Libraries/ZO_KeybindButton/ZO_KeybindButton.lua:265: in function 'ZO_KeybindButtonTemplate_OnMouseUp'
ZO_Dialog1Button2_MouseUp:3: in function '(main chunk)'

**Comment by klingo** [comment]
Hi, can you please try the following as suggested by the author of LibAddonMenu?
https://www.esoui.com/downloads/info7-LibAddonMenu.html#info

> IMPORTANT
In case you get an error that contains text like this:
user:/AddOns/< some other addon >/Libs/LibAddonMenu-2.0
Make sure to delete all LibAddonMenu-2.0 folders in your AddOns folder and install the latest version of LibAddonMenu-2.0 separately.
