### ISSUE TITLE
Personal Assistant ESO Add-on issue

### ISSUE THREAD

**Issue by rezznor68** [klingo/ESO-PersonalAssistant#371]
I receive the following error when I installed PersonalAssistant 2.5.17 in ESO. I tried running just that add-on by itself, I tried shift deleting and redownoading from ESOUI instead of Minion. I also tried using files from someone who has the add-on working on their PC. I tried removing all my saved variables in ESO Live.

user:/AddOns/PersonalAssistant/PersonalAssistantRepair/Profiles/PARepairSavedVarsPatcher.lua:30: number expected for loop variables
stack traceback:
user:/AddOns/PersonalAssistant/PersonalAssistantRepair/Profiles/PARepairSavedVarsPatcher.lua:30: in function '_applyPatch_2_5_11'
<Locals> savedVarsVersion = 20511, isPatchingNeeded = T, PASavedVars = [table:1]{} </Locals>|r
user:/AddOns/PersonalAssistant/PersonalAssistantRepair/Profiles/PARepairSavedVarsPatcher.lua:45: in function 'applyPatchIfNeeded'
user:/AddOns/PersonalAssistant/PersonalAssistantRepair/PersonalAssistantRepair.lua:49: in function 'initAddon'
<Locals> _ = 65536, addOnName = "PersonalAssistantRepair", PASavedVars = [table:1] </Locals>|r

Any assistance would help!

Thank you,

**Comment by klingo** [comment]
Apologies for reacting so late.
It looks like your SavedVariables got corrupted in a previous version of PersonalAssistant which is breaking the 'upgrade' to the latest version now. I will try to add a fix in the next version.
