### ISSUE TITLE
PAJunk.lua issue with itemQuality and operator 

### ISSUE THREAD

**Issue by ditolesto** [klingo/ESO-PersonalAssistant#372]
When AutoJunk is enabled, and the code detects there is a junk decision to be made on item quality, the addon has an issue at line 461 of PAjunk.lua:

```
local qualityThreshold = savedVarsGroup.autoMarkQualityThreshold
-->        if qualityThreshold ~= PAC.ITEM_QUALITY.DISABLED and itemQuality <= qualityThreshold then
```

and the error code states that operator < is not supported for number < string.

I think this means that when there is the decision to be made based on item quality, we are comparing a string against a number and that fails.

In the screenshot the variables itemQuality = 1 and qualityThreshold = Normal

![personalassistanterror](https://user-images.githubusercontent.com/26855246/125121452-dd51e400-e0eb-11eb-8e05-b02fd239bb50.jpg)

**Comment by ditolesto** [comment]
I ended up modifying PAJunkMenuDefaults.lua, and set the autoMarkQualityThreshold parameter to 1 (Normal) and that set the default threshold for the category, so i didn't need to use the dropdown.

The mapping of the itemQuality number and the String version of the dropdown is broken.

Unfortunately i wasn't able to trace how to make sure this mapping is correct, so ended up modifying the default instead.

**Comment by klingo** [comment]
Your analysis is correct, although it should not happen that the string representation of the quality level is stored in the SavedVariables - it should always use the numeric representation (which works fine).

Unfortuantely, I'm not sure what I can do here, since I don't really see in the code how this wrong assignment could have happened :(
Please let me know though if this should happen again, even after your manual fix.

**Comment by FLY1NGSQU1RR3L** [comment]
@klingo  - is the PAJSavedVars table being shared across multiple of your mods?  Maybe there's a copy/paste error somewhere that is updating your table with a string from outside?  I don't see where the error is being introduced here either, but I'm not familiar enough with how to step through this while running the mod in-game yet.  Just started looking today after I hit the same error.

If you had a sec to just point me to when the table gets created to when it gets patched maybe we can help you find this bug.

![image](https://user-images.githubusercontent.com/14060191/139597243-b49f099c-c35f-466a-937c-934333c45157.png)
