### ISSUE TITLE
PAB: Add option to bank intricate Items

### ISSUE THREAD

**Issue by MarcoPolo184** [klingo/ESO-PersonalAssistant#78]
Last crafting writ rewards I need to handle manually atm.

**Comment by klingo** [comment]
Hi, I'm not sure if I understand you correctly ; is there an issue with [Intricate] items from Writ rewards?
Or would like to have an option to deposit/withdraw ANY [Intricate] item to the bank?

**Comment by MarcoPolo184** [comment]
Hey, there is no issue, it's only a suggestion to add an option to deposit/withdraw any intricate items. I use your addon mainly to sort rewards from writs on alts and these are the only items I can't set a rule for.
Thanks for the great addon!^^

**Comment by klingo** [comment]
Thanks for the positive feedback! :)
Ah yes that sounds like a good idea, I will include that in the next update.
